// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fills.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFill = `-- name: CreateFill :execresult
INSERT INTO fills (order_id, fill_price, fill_quantity, fee)
VALUES (?, ?, ?, ?)
`

type CreateFillParams struct {
	OrderID      int64  `db:"order_id" json:"order_id"`
	FillPrice    string `db:"fill_price" json:"fill_price"`
	FillQuantity int64  `db:"fill_quantity" json:"fill_quantity"`
	Fee          string `db:"fee" json:"fee"`
}

func (q *Queries) CreateFill(ctx context.Context, arg CreateFillParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFill,
		arg.OrderID,
		arg.FillPrice,
		arg.FillQuantity,
		arg.Fee,
	)
}

const listFillsByOrder = `-- name: ListFillsByOrder :many
SELECT id, order_id, fill_price, fill_quantity, fee, filled_at
FROM fills
WHERE order_id = ?
ORDER BY filled_at ASC
`

func (q *Queries) ListFillsByOrder(ctx context.Context, orderID int64) ([]Fill, error) {
	rows, err := q.db.QueryContext(ctx, listFillsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fill{}
	for rows.Next() {
		var i Fill
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FillPrice,
			&i.FillQuantity,
			&i.Fee,
			&i.FilledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
