// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type OrdersOrderType string

const (
	OrdersOrderTypeMARKET OrdersOrderType = "MARKET"
	OrdersOrderTypeLIMIT  OrdersOrderType = "LIMIT"
)

func (e *OrdersOrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersOrderType(s)
	case string:
		*e = OrdersOrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersOrderType: %T", src)
	}
	return nil
}

type NullOrdersOrderType struct {
	OrdersOrderType OrdersOrderType `json:"orders_order_type"`
	Valid           bool            `json:"valid"` // Valid is true if OrdersOrderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersOrderType) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersOrderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersOrderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersOrderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersOrderType), nil
}

type OrdersSide string

const (
	OrdersSideBUY  OrdersSide = "BUY"
	OrdersSideSELL OrdersSide = "SELL"
)

func (e *OrdersSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersSide(s)
	case string:
		*e = OrdersSide(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersSide: %T", src)
	}
	return nil
}

type NullOrdersSide struct {
	OrdersSide OrdersSide `json:"orders_side"`
	Valid      bool       `json:"valid"` // Valid is true if OrdersSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersSide) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersSide), nil
}

type OrdersStatus string

const (
	OrdersStatusPENDING  OrdersStatus = "PENDING"
	OrdersStatusFILLED   OrdersStatus = "FILLED"
	OrdersStatusCANCELED OrdersStatus = "CANCELED"
	OrdersStatusREJECTED OrdersStatus = "REJECTED"
)

func (e *OrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersStatus(s)
	case string:
		*e = OrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersStatus: %T", src)
	}
	return nil
}

type NullOrdersStatus struct {
	OrdersStatus OrdersStatus `json:"orders_status"`
	Valid        bool         `json:"valid"` // Valid is true if OrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersStatus), nil
}

type StrategyRunsStatus string

const (
	StrategyRunsStatusRUNNING StrategyRunsStatus = "RUNNING"
	StrategyRunsStatusSUCCESS StrategyRunsStatus = "SUCCESS"
	StrategyRunsStatusFAILED  StrategyRunsStatus = "FAILED"
)

func (e *StrategyRunsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StrategyRunsStatus(s)
	case string:
		*e = StrategyRunsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StrategyRunsStatus: %T", src)
	}
	return nil
}

type NullStrategyRunsStatus struct {
	StrategyRunsStatus StrategyRunsStatus `json:"strategy_runs_status"`
	Valid              bool               `json:"valid"` // Valid is true if StrategyRunsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStrategyRunsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StrategyRunsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StrategyRunsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStrategyRunsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StrategyRunsStatus), nil
}

type Fill struct {
	ID           int64     `db:"id" json:"id"`
	OrderID      int64     `db:"order_id" json:"order_id"`
	FillPrice    string    `db:"fill_price" json:"fill_price"`
	FillQuantity int64     `db:"fill_quantity" json:"fill_quantity"`
	Fee          string    `db:"fee" json:"fee"`
	FilledAt     time.Time `db:"filled_at" json:"filled_at"`
}

type Order struct {
	ID              int64           `db:"id" json:"id"`
	PortfolioID     int64           `db:"portfolio_id" json:"portfolio_id"`
	Symbol          string          `db:"symbol" json:"symbol"`
	Side            OrdersSide      `db:"side" json:"side"`
	OrderType       OrdersOrderType `db:"order_type" json:"order_type"`
	Status          OrdersStatus    `db:"status" json:"status"`
	Quantity        int64           `db:"quantity" json:"quantity"`
	Price           string          `db:"price" json:"price"`
	ExternalOrderID sql.NullString  `db:"external_order_id" json:"external_order_id"`
	SubmittedAt     time.Time       `db:"submitted_at" json:"submitted_at"`
	FilledAt        sql.NullTime    `db:"filled_at" json:"filled_at"`
}

type Portfolio struct {
	ID          int64     `db:"id" json:"id"`
	UserID      int64     `db:"user_id" json:"user_id"`
	Name        string    `db:"name" json:"name"`
	CashBalance string    `db:"cash_balance" json:"cash_balance"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type Position struct {
	ID          int64     `db:"id" json:"id"`
	PortfolioID int64     `db:"portfolio_id" json:"portfolio_id"`
	Symbol      string    `db:"symbol" json:"symbol"`
	Quantity    int64     `db:"quantity" json:"quantity"`
	AvgPrice    string    `db:"avg_price" json:"avg_price"`
	LastPrice   string    `db:"last_price" json:"last_price"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type StrategyRun struct {
	ID           int64              `db:"id" json:"id"`
	PortfolioID  int64              `db:"portfolio_id" json:"portfolio_id"`
	StrategyName string             `db:"strategy_name" json:"strategy_name"`
	Status       StrategyRunsStatus `db:"status" json:"status"`
	StartedAt    time.Time          `db:"started_at" json:"started_at"`
	FinishedAt   sql.NullTime       `db:"finished_at" json:"finished_at"`
	ErrorMessage sql.NullString     `db:"error_message" json:"error_message"`
}

type User struct {
	ID        int64     `db:"id" json:"id"`
	LoginID   string    `db:"login_id" json:"login_id"`
	Password  string    `db:"password" json:"password"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}
