// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO orders (
  portfolio_id, symbol, side, order_type, status, quantity, price, external_order_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	PortfolioID     int64           `db:"portfolio_id" json:"portfolio_id"`
	Symbol          string          `db:"symbol" json:"symbol"`
	Side            OrdersSide      `db:"side" json:"side"`
	OrderType       OrdersOrderType `db:"order_type" json:"order_type"`
	Status          OrdersStatus    `db:"status" json:"status"`
	Quantity        int64           `db:"quantity" json:"quantity"`
	Price           string          `db:"price" json:"price"`
	ExternalOrderID sql.NullString  `db:"external_order_id" json:"external_order_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder,
		arg.PortfolioID,
		arg.Symbol,
		arg.Side,
		arg.OrderType,
		arg.Status,
		arg.Quantity,
		arg.Price,
		arg.ExternalOrderID,
	)
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, portfolio_id, symbol, side, order_type, status, quantity, price,
       external_order_id, submitted_at, filled_at
FROM orders
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Symbol,
		&i.Side,
		&i.OrderType,
		&i.Status,
		&i.Quantity,
		&i.Price,
		&i.ExternalOrderID,
		&i.SubmittedAt,
		&i.FilledAt,
	)
	return i, err
}

const listOrdersByPortfolio = `-- name: ListOrdersByPortfolio :many
SELECT id, portfolio_id, symbol, side, order_type, status, quantity, price,
       external_order_id, submitted_at, filled_at
FROM orders
WHERE portfolio_id = ?
ORDER BY submitted_at DESC
LIMIT ?
`

type ListOrdersByPortfolioParams struct {
	PortfolioID int64 `db:"portfolio_id" json:"portfolio_id"`
	Limit       int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListOrdersByPortfolio(ctx context.Context, arg ListOrdersByPortfolioParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByPortfolio, arg.PortfolioID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Symbol,
			&i.Side,
			&i.OrderType,
			&i.Status,
			&i.Quantity,
			&i.Price,
			&i.ExternalOrderID,
			&i.SubmittedAt,
			&i.FilledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = ?, filled_at = ?
WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status   OrdersStatus `db:"status" json:"status"`
	FilledAt sql.NullTime `db:"filled_at" json:"filled_at"`
	ID       int64        `db:"id" json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.FilledAt, arg.ID)
	return err
}
