// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolios.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPortfolio = `-- name: CreatePortfolio :execresult
INSERT INTO portfolios (user_id, name, cash_balance)
VALUES (?, ?, ?)
`

type CreatePortfolioParams struct {
	UserID      int64  `db:"user_id" json:"user_id"`
	Name        string `db:"name" json:"name"`
	CashBalance string `db:"cash_balance" json:"cash_balance"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPortfolio, arg.UserID, arg.Name, arg.CashBalance)
}

const getPortfolioByID = `-- name: GetPortfolioByID :one
SELECT id, user_id, name, cash_balance, created_at, updated_at
FROM portfolios
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPortfolioByID(ctx context.Context, id int64) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioByID, id)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPortfoliosByUser = `-- name: ListPortfoliosByUser :many
SELECT id, user_id, name, cash_balance, created_at, updated_at
FROM portfolios
WHERE user_id = ?
ORDER BY id DESC
`

func (q *Queries) ListPortfoliosByUser(ctx context.Context, userID int64) ([]Portfolio, error) {
	rows, err := q.db.QueryContext(ctx, listPortfoliosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CashBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
