// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: positions.sql

package sqlc

import (
	"context"
)

const listPositionsByPortfolio = `-- name: ListPositionsByPortfolio :many
SELECT id, portfolio_id, symbol, quantity, avg_price, last_price, updated_at
FROM positions
WHERE portfolio_id = ?
ORDER BY symbol ASC
`

func (q *Queries) ListPositionsByPortfolio(ctx context.Context, portfolioID int64) ([]Position, error) {
	rows, err := q.db.QueryContext(ctx, listPositionsByPortfolio, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Symbol,
			&i.Quantity,
			&i.AvgPrice,
			&i.LastPrice,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPosition = `-- name: UpsertPosition :exec
INSERT INTO positions (portfolio_id, symbol, quantity, avg_price, last_price)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  quantity = VALUES(quantity),
  avg_price = VALUES(avg_price),
  last_price = VALUES(last_price),
  updated_at = CURRENT_TIMESTAMP
`

type UpsertPositionParams struct {
	PortfolioID int64  `db:"portfolio_id" json:"portfolio_id"`
	Symbol      string `db:"symbol" json:"symbol"`
	Quantity    int64  `db:"quantity" json:"quantity"`
	AvgPrice    string `db:"avg_price" json:"avg_price"`
	LastPrice   string `db:"last_price" json:"last_price"`
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) error {
	_, err := q.db.ExecContext(ctx, upsertPosition,
		arg.PortfolioID,
		arg.Symbol,
		arg.Quantity,
		arg.AvgPrice,
		arg.LastPrice,
	)
	return err
}
