// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateFill(ctx context.Context, arg CreateFillParams) (sql.Result, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error)
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (sql.Result, error)
	CreateStrategyRun(ctx context.Context, arg CreateStrategyRunParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	FinishStrategyRun(ctx context.Context, arg FinishStrategyRunParams) error
	GetOrderByID(ctx context.Context, id int64) (Order, error)
	GetPortfolioByID(ctx context.Context, id int64) (Portfolio, error)
	GetUserByLoginID(ctx context.Context, loginID string) (User, error)
	ListFillsByOrder(ctx context.Context, orderID int64) ([]Fill, error)
	ListOrdersByPortfolio(ctx context.Context, arg ListOrdersByPortfolioParams) ([]Order, error)
	ListPortfoliosByUser(ctx context.Context, userID int64) ([]Portfolio, error)
	ListPositionsByPortfolio(ctx context.Context, portfolioID int64) ([]Position, error)
	ListStrategyRunsByPortfolio(ctx context.Context, arg ListStrategyRunsByPortfolioParams) ([]StrategyRun, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpsertPosition(ctx context.Context, arg UpsertPositionParams) error
}

var _ Querier = (*Queries)(nil)
