// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: strategy_runs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createStrategyRun = `-- name: CreateStrategyRun :execresult
INSERT INTO strategy_runs (portfolio_id, strategy_name, status)
VALUES (?, ?, 'RUNNING')
`

type CreateStrategyRunParams struct {
	PortfolioID  int64  `db:"portfolio_id" json:"portfolio_id"`
	StrategyName string `db:"strategy_name" json:"strategy_name"`
}

func (q *Queries) CreateStrategyRun(ctx context.Context, arg CreateStrategyRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createStrategyRun, arg.PortfolioID, arg.StrategyName)
}

const finishStrategyRun = `-- name: FinishStrategyRun :exec
UPDATE strategy_runs
SET status = ?, finished_at = CURRENT_TIMESTAMP, error_message = ?
WHERE id = ?
`

type FinishStrategyRunParams struct {
	Status       StrategyRunsStatus `db:"status" json:"status"`
	ErrorMessage sql.NullString     `db:"error_message" json:"error_message"`
	ID           int64              `db:"id" json:"id"`
}

func (q *Queries) FinishStrategyRun(ctx context.Context, arg FinishStrategyRunParams) error {
	_, err := q.db.ExecContext(ctx, finishStrategyRun, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}

const listStrategyRunsByPortfolio = `-- name: ListStrategyRunsByPortfolio :many
SELECT id, portfolio_id, strategy_name, status, started_at, finished_at, error_message
FROM strategy_runs
WHERE portfolio_id = ?
ORDER BY started_at DESC
LIMIT ?
`

type ListStrategyRunsByPortfolioParams struct {
	PortfolioID int64 `db:"portfolio_id" json:"portfolio_id"`
	Limit       int32 `db:"limit" json:"limit"`
}

func (q *Queries) ListStrategyRunsByPortfolio(ctx context.Context, arg ListStrategyRunsByPortfolioParams) ([]StrategyRun, error) {
	rows, err := q.db.QueryContext(ctx, listStrategyRunsByPortfolio, arg.PortfolioID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StrategyRun{}
	for rows.Next() {
		var i StrategyRun
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.StrategyName,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
