// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (login_id, password)
VALUES (?, ?)
`

type CreateUserParams struct {
	LoginID  string `db:"login_id" json:"login_id"`
	Password string `db:"password" json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.LoginID, arg.Password)
}

const getUserByLoginID = `-- name: GetUserByLoginID :one
SELECT id, login_id, password, created_at
FROM users
WHERE login_id = ?
LIMIT 1
`

func (q *Queries) GetUserByLoginID(ctx context.Context, loginID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLoginID, loginID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LoginID,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
